增加分类和标签的聚合页链接
flysnow-org/maupassant-hugo pull request #113
Opened 2020-08-19 09:18 UTC by luodaoyi

我重新fork了 这下只有一条提交记录了了哈哈

2020-08-19 10:31 UTC, rujews requested changes

2020-08-19 10:31 UTC, rujews commented on layouts/partials/tags.html
> +<h3 class="widget-title"><a href="tags">标签</a></h3>
应该使用绝对路径`/tags`

2020-08-19 10:31 UTC, rujews commented
记得是一个commit，使用--force强制推送

2020-08-19 15:56 UTC, luodaoyi commented on layouts/partials/tags.html
> +<h3 class="widget-title"><a href="tags">标签</a></h3>
一紧张搞忘了

2020-08-19 15:57 UTC, luodaoyi commented
好了  这下还学会用git  rebase -i xxx了

2020-08-20 00:49 UTC, rujews approved these changes

2020-08-20 00:51 UTC, merged